openMyNotes: Open in My Notes
openStudyPad: Open in Study Pad (%s)
noteText: Footnotes (%s)
crossReferenceText: Cross references
findAllOccurrences: Find all occurrences
reportError: Report an error
errorTitle: Error occurred
warningTitle: Warning
normalTitle: Please note
footnoteTypeUndefined: Undefined type
footnoteTypeStudy: Study
footnoteTypeExplanation: Explanation
footnoteTypeVariant: Variant
footnoteTypeAlternative: Alternative
footnoteTypeTranslation: Translation
clearLog: Clear error log
editNote: Edit
editNotePlaceholder: Edit a note for bookmark
editTextPlaceholder: Tap to edit text
inputPlaceholder: Write here
inputReference: Enter Bible reference
assignLabels: Labels
bookmarkAccurate: Bookmark was created in %s
bookmarkInaccurate: Bookmark book information not stored, content is displayed in %s.
defaultBook: default Bible document
ok: OK
yes: Yes
ambiguousSelection: Which action do you wish to take?
cancel: Cancel
removeBookmarkConfirmationTitle: Remove bookmark?
removeBookmarkConfirmation: Are you sure you want to remove this bookmark?
closeModal: Close
createdAt: "Created: %s"
lastUpdatedOn: "Last updated: %s"
strongsLink: Open Strongs (%s)
studyPadLink: Open study pad
externalLink: Open external link
referenceLink: Open reference link
openFootnote: Open footnote
openBookmark: Open bookmark (%s)
noMyNotesTitle: No My Notes for this chapter.
noMyNotesDescription: >
  Get started by creating bookmarks in a Bible document.
  The bookmarks will then appear here and you can add your personal notes to them.
emptyStudyPad: >
  Empty study pad. Start adding to this study pad by creating text entries here
  or by creating bookmarks with a bookmark label that corresponds with this study pad.
studyPadModalTitle: Edit study pad entry
doYouWantToDeleteEntry: Are you sure you want to delete this study pad entry?
removeStudyPadConfirmationTitle: Remove study pad entry?
dragHelp: You can drag & drop item to re-order study pad
saved: saved
openAll: Open all references
editBookmarkPlaceholder: Tap to edit My Notes for this bookmark
onlyLabel: Only label
wholeBookmark: Whole bookmark
otherNoteText: Other note
assignLabelsMenuEntry: Assign labels
jumpToStudyPad: Jump to Study Pad
setAsPrimaryLabel: Set as primary label
